# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.destroycreate([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)

  
# ActiveRecord::Base.connection.delete("delete from usecases_vocabs")
# ActiveRecord::Base.connection.delete("delete from topics_usecases")


#DELETE ALL SEED DATA
Vocab.all.each do |r| r.destroy end
Usecase.all.each do |r| r.destroy end
Topic.all.each do |r| r.destroy end
Usage.all.each do |r| r.destroy end
Topiccluster.all.each do |r| r.destroy end
Usecasecluster.all.each do |r| r.destroy end
Vocabtype.all.each do |r| r.destroy end

puts "Destroyed all previous records\n\n"

puts "Creating topicclusters & topics....\n\n"

topiccluster = Topiccluster.create(:name =>"CM.Conceptual Models and KOS")
Topic.create(:name => "CM.KNOWLEDGE-REPRESENTATION", :topiccluster_id => topiccluster.id)
Topic.create(:name => "CM.FRS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "CM.NON-BIBLIO", :topiccluster_id => topiccluster.id)
Topic.create(:name => "CM.CITATIONS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "CM.APP-PROFILES", :topiccluster_id => topiccluster.id)
Topic.create(:name => "Other (Not in initial topic list) : archival material", :topiccluster_id => topiccluster.id)


topiccluster = Topiccluster.create(:name =>"LLD.Applying SemWeb Technology to Library Data (Implementation)")
Topic.create(:name => "LLD.LEGACY", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.AVAILABLE-LINKED-DATA", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.VOCABS-STATUS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.MARC2LLD", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.REFERENCE-MODEL-FIT", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.COMMON-MODEL", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.AUTHORITIES", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.VOCABS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.SPECIFIC-VOCABS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.SKOS-FOR-INTEGRATED-KOS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.SKOS-MULTILINGUAL", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.SKOS-LIB-KOS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.PERSON-METADATA", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.PERSON-NAMES", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.IDENTIFIERS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.INSTITUTION-IDS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.LEGACY-IDS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "LLD.NAMESPACES", :topiccluster_id => topiccluster.id)

topiccluster = Topiccluster.create(:name =>"SW.Semantic Web Environmental Issues")
Topic.create(:name => "SW.IDENTIFIERS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.LINKING", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.LINKING-INVENTORY", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.CROSS-LINKING-VOCABS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.IDENTIFIERS-RWO", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.LD-V-RECORDS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.LD-PACKAGING", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.PROVENANCE", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.REST", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.CONVERSION", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.SKOS-EXTENSIONS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "SW.DATA-EXTRACTION", :topiccluster_id => topiccluster.id)

topiccluster = Topiccluster.create(:name =>"DATA.Management of data and distribution")
Topic.create(:name => "DATA.GENERAL", :topiccluster_id => topiccluster.id)
Topic.create(:name => "DATA.VOCABS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "DATA.VERSIONING", :topiccluster_id => topiccluster.id)
Topic.create(:name => "DATA.DISSEMINATION", :topiccluster_id => topiccluster.id)
Topic.create(:name => "DATA.CHANGES", :topiccluster_id => topiccluster.id)
Topic.create(:name => "DATA.OBSOLETE-VOCABS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "DATA.ARCHITECTURE", :topiccluster_id => topiccluster.id)
Topic.create(:name => "DATA.CACHING", :topiccluster_id => topiccluster.id)
Topic.create(:name => "DATA.ONTOLOGY-DISCOVERY", :topiccluster_id => topiccluster.id)
Topic.create(:name => "DATA.SEARCH-OPTIMISATION", :topiccluster_id => topiccluster.id)

topiccluster = Topiccluster.create(:name =>"MGT.Community and Management Issues")
Topic.create(:name => "MGT.RIGHTS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.LICENSES", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.GUIDANCE", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.WORKFLOWS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.BIZ-MODELS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.PATTERNS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.COMMUNITY-BUILDING", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.TRAINING", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.LEGACY-MAPPING", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.STANDARDS-PARTICIPATION", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.OUTREACH", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.NEW-EFFORTS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.NEXT-STEPS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.FUTURE-WGS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "MGT.BEST-PRACTICES-GP", :topiccluster_id => topiccluster.id)

topiccluster = Topiccluster.create(:name =>"USE.Consuming and using library data")
Topic.create(:name => "USE.END_USERS", :topiccluster_id => topiccluster.id)
Topic.create(:name => "USE.COMPUTATIONAL", :topiccluster_id => topiccluster.id)
Topic.create(:name => "USE.PRO", :topiccluster_id => topiccluster.id)

puts "Creating vocabs....\n\n"
vocabtype = Vocabtype.create(:name => "UNCLASSIFIED")
Vocab.create(:name => "Bibliographic Ontology",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "CIDOC-CRM",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "OWL",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "CITO",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "SURF",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "RDFS",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "W3C Media Ontology",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "BIO",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Music Ontology",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Organisational Ontology",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Dewey.info",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "LCSH",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Thesaurus for Graphic Materials",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Library of Congress Name Authority File",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Freebase",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Rameau",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Linked Data Services der DNB",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "EDM",:vocabtype_id => vocabtype.id)
# Vocab.create(:name => "Instituto Geográfico Nacional (España)",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "PRONOM",:vocabtype_id => vocabtype.id)


vocabtype = Vocabtype.create(:name => "Existing published Vocabularies available for reuse")
# Vocab.create(:name => "",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "FOAF",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "RDA",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "RDA Group 1 Elements",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "RDA Group 2 Elements",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "SKOS",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "FRBR",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "FRBR Core",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "FRBRer",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "FRAD",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "FRSAD",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "OAI-ORE",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "DOAP",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "LoC Preservation Vocabularies",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "ISBD",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "BIBO",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "DC Terms",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "DC Types",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "EXIF",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "OPM",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "W3C Geo vocab",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "UMBEL",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "hcard",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "vcard",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "lexvo",:vocabtype_id => vocabtype.id)

vocabtype = Vocabtype.create(:name => "Local or special vocabularies")
Vocab.create(:name => "P20vocab",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "GND (Gemeinsame Normdatei) namespace",:vocabtype_id => vocabtype.id)

vocabtype = Vocabtype.create(:name => "Work in progress to create ontologies for")
Vocab.create(:name => "MADS",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "ISAD(G)",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "MODS",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "PREMIS",:vocabtype_id => vocabtype.id)

vocabtype = Vocabtype.create(:name => "Reference value vocabularies")
Vocab.create(:name => "VIAF",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Geonames",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "ULAN",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "TGN",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "DDC",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "UDC",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Iconclass",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "dbPedia",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "ASFA Thesaurus",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "Fisheries Reference Metadata",:vocabtype_id => vocabtype.id)
Vocab.create(:name => "USDA National Agricultural Library",:vocabtype_id => vocabtype.id)

# USE-CASES
# Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("").id)
puts "Creating use cases....\n\n"

usecasecluster = Usecasecluster.create(:name => 'Bibliographic data')
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Bibliographic Network")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FRBR Core").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Bibliographic Ontology").id)
    usecase.topics << Topic.find_by_name('CM.FRS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Open Library Data")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("RDA Group 1 Elements").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FRBR").id)
    usecase.topics << Topic.find_by_name('CM.FRS')
    usecase.topics << Topic.find_by_name('LLD.AVAILABLE-LINKED-DATA')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Identification and deduplication of library records")
    usecase.topics << Topic.find_by_name('LLD.LEGACY')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Regional Catalog")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("RDA").id)
    usecase.topics << Topic.find_by_name('CM.FRS')
    usecase.topics << Topic.find_by_name('LLD.AVAILABLE-LINKED-DATA')
    usecase.topics << Topic.find_by_name('SW.CROSS-LINKING-VOCABS')
    usecase.topics << Topic.find_by_name('DATA.GENERAL')
    usecase.topics << Topic.find_by_name('MGT.LICENSES')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Data BNF")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("RDA").id)
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Pode")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FRBR Core").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Lexvo").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Geonames").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Dewey.info").id)
    usecase.topics << Topic.find_by_name('USE.END_USERS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Polymath Virtual Library")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("dbPedia").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("VIAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("LCSH").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("RAMEAU").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Linked Data Services der DNB").id)
    # Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Instituto Geográfico Nacional (España)").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("EDM").id)
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Community Information Service")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("CITO").id)
    
usecasecluster = Usecasecluster.create(:name => 'Authority data')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Authority Data Enrichment")
    Usage.create(:description =>"for works",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("RDA Group 1 Elements").id)
    Usage.create(:description =>"for persons, corporate bodies",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"for persons, corporate bodies and families",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("RDA Group 2 Elements").id)
    usecase.topics << Topic.find_by_name('SW.CROSS-LINKING-VOCABS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Virtual International Authority File (VIAF)")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("VIAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("OWL").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("UMBEL").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FRBR").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    usecase.topics << Topic.find_by_name('CM.FRS')
    usecase.topics << Topic.find_by_name('LLD.AVAILABLE-LINKED-DATA')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "FAO Authority Description Concept Scheme")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("RDA").id)
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Linked Data Service of the German National Library")
    usecase.topics << Topic.find_by_name('LLD.AUTHORITIES')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "International Registry for Authors")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "AuthorClaim")

usecasecluster = Usecasecluster.create(:name => 'Vocabulary alignment')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Subject Search")
    usecase.topics << Topic.find_by_name('CM.FRS')
    usecase.topics << Topic.find_by_name('SW.IDENTIFIERS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Language Technology")
    usecase.topics << Topic.find_by_name('USE.COMPUTATIONAL')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Vocabulary Merging")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    usecase.topics << Topic.find_by_name('SW.CROSS-LINKING-VOCABS')
    usecase.topics << Topic.find_by_name('DATA.CACHING')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Component Vocabularies")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("MADS").id)
    usecase.topics << Topic.find_by_name('CM.FRS')
    usecase.topics << Topic.find_by_name('DATA.VOCABS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Browsing and searching in data repositories annotated with different thesauri")
    usecase.topics << Topic.find_by_name('SW.CROSS-LINKING-VOCABS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "AGROVOC Thesaurus")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("OWL").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("ASFA Thesaurus").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Fisheries Reference Metadata").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("USDA National Agricultural Library").id)
    usecase.topics << Topic.find_by_name('LLD.SKOS-MULTILINGUAL')
    usecase.topics << Topic.find_by_name('LLD.SKOS-LIB-KOS')
    usecase.topics << Topic.find_by_name('SW.SKOS-EXTENSIONS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "AGRIS")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Civil War Data 150")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("dbPedia").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("LCSH").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Freebase").id)

usecasecluster = Usecasecluster.create(:name => 'Archives and heterogeneous data')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Digital Preservation")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("LoC Preservation Vocabularies").id)
    Usage.create(:description =>"to describe the structure of complex data objects",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("OAI-ORE").id)
    Usage.create(:description =>"to describe software agents",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DOAP").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("PRONOM").id)
    usecase.topics << Topic.find_by_name('CM.NON-BIBLIO')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Europeana")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("OAI-ORE").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("CIDOC-CRM").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FRBR").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("VIAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Geonames").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("ULAN").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("TGN").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DDC").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("UDC").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Iconclass").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("dbPedia").id)
    usecase.topics << Topic.find_by_name('SW.LD-V-RECORDS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Photo museum case")
    usecase.topics << Topic.find_by_name('Other (Not in initial topic list) : archival material')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Radio Station Archive Digitisation")
    usecase.topics << Topic.find_by_name('Other (Not in initial topic list) : archival material')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "LOCAH")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FRBR").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("RDFS").id)
    usecase.topics << Topic.find_by_name('Other (Not in initial topic list) : archival material')
    usecase.topics << Topic.find_by_name('MGT.OUTREACH')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Archipel project")
    usecase.topics << Topic.find_by_name('MGT.OUTREACH')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Recollection")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("LCSH").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Thesaurus for Graphic Materials").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Library of Congress Name Authority File").id)
    usecase.topics << Topic.find_by_name('USE.PRO')

usecasecluster = Usecasecluster.create(:name => 'Digital objects')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Publishing 20th Century Press Archives")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("OAI-ORE").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("EXIF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("P20vocab").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("RDA Group 2 Elements").id)
    usecase.topics << Topic.find_by_name('CM.NON-BIBLIO')
    usecase.topics << Topic.find_by_name('DATA.GENERAL')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "NDNP")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("OAI-ORE").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Bibliographic Ontology").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FRBR").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("EXIF").id)
    usecase.topics << Topic.find_by_name('CM.NON-BIBLIO')
        usecase.topics << Topic.find_by_name('MGT.TRAINING')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Digital Text Repository")
    usecase.topics << Topic.find_by_name('SW.IDENTIFIERS-RWO')
    usecase.topics << Topic.find_by_name('USE.COMPUTATIONAL')

usecasecluster = Usecasecluster.create(:name => 'Citations')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Citation of Datasets")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("OPM").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("CITO").id)
    usecase.topics << Topic.find_by_name('CM.CITATIONS')
    usecase.topics << Topic.find_by_name('MGT.OUTREACH')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Enhanced Publications")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("OAI-ORE").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Types").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SURF").id)
    usecase.topics << Topic.find_by_name('CM.FRS')
    usecase.topics << Topic.find_by_name('CM.NON-BIBLIO')
    usecase.topics << Topic.find_by_name('CM.CITATIONS')
    usecase.topics << Topic.find_by_name('LLD.IDENTIFIERS')
    usecase.topics << Topic.find_by_name('MGT.RIGHTS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Mapping Scholarly Debate")

usecasecluster = Usecasecluster.create(:name => '[NOT YET CLUSTERED]')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Bridging OWL and UML")
    usecase.topics << Topic.find_by_name('CM.APP-PROFILES')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "NEP: New Economics Papers")
    usecase.topics << Topic.find_by_name('CM.FRS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Ranking Search Results by Popularity using Circulation Data")
    usecase.topics << Topic.find_by_name('CM.NON-BIBLIO')
    usecase.topics << Topic.find_by_name('LLD.SPECIFIC-VOCABS')
    usecase.topics << Topic.find_by_name('MGT.RIGHTS')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Use Cases NLL Digitized Map Archive")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Geonames").id)
    usecase.topics << Topic.find_by_name('CM.NON-BIBLIO')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Library Address Data")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Geonames").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("hcard").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("vcard").id)
    usecase.topics << Topic.find_by_name('CM.NON-BIBLIO')
    usecase.topics << Topic.find_by_name('LLD.IDENTIFIERS')
    usecase.topics << Topic.find_by_name('DATA.CHANGES')
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Collecting material related to courses at The Open University")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("SKOS").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("W3C Media Ontology").id)
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"
  usecase = Usecase.create(:usecasecluster_id => usecasecluster.id,:name => "Talis Prism 3")
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("FOAF").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIBO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("DC Terms").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("BIO").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Music Ontology").id)
    Usage.create(:description =>"",:usecase_id => usecase.id,:vocab_id => Vocab.find_by_name("Organisational Ontology").id)
    puts "successfully created record and associations for usecase with name '#{usecase.name}'"

puts "ALL DONE OK"
